### ISSUE TITLE
interest subfeatures

### ISSUE THREAD

**Issue by louking** [louking/runningroutes#9]
want the following

- [x] select of interest to reload page with interest oriented navigation
- [x] new page to remember last interest selected (localStorage ?) #11
- [x] separate tabs to be able to work on different interests (sessionStorage ?) #12
- [x] reinitialize application shouldn't lose interest select values
- [ ] ~~hand crafted url with interest should be set into interest select~~
